# Owner: 정태훈
# Scope: Application Runtime / GitOps
# Related: seokpan-gitops#29

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml

images:
  - name: harbor.seokpan.soldesk.store/seokpan/frontend
    newName: harbor.seokpan.soldesk.store/seokpan/frontend
    digest: sha256:123203a4c5a5490690164deb68dffd929b6b9a45e36476e521f5c95ec70b0701
