# Owner: 정태훈
# Scope: Application Runtime / GitOps
# Related: seokpan-gitops#29, seokpan-gitops#35, seokpan-app#50

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - configmap.yaml
  - database-ca-configmap.yaml
  - deployment.yaml
  - pdb.yaml
  - service.yaml

images:
  - name: harbor.seokpan.soldesk.store/seokpan/backend
    newName: harbor.seokpan.soldesk.store/seokpan/backend
    digest: sha256:65c59b16b23f771b3f22e6bbad9343760ca43a09359af8c7f0fba609dfab3684
