# Owner: 정태훈
# Scope: Application Runtime / GitOps
# Related: seokpan-gitops#29, seokpan-gitops#35, seokpan-app#50

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - configmap.yaml
  - database-ca-configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: harbor.seokpan.soldesk.store/seokpan/backend
    newName: harbor.seokpan.soldesk.store/seokpan/backend
    digest: sha256:4e57c150ffc04f41d5124e1c41c535d4edbc22edc40481ac20d4b474c5a7ac4d
