# Owner: 정태훈
# Scope: Application Runtime / GitOps
# Related: seokpan-gitops#29, seokpan-gitops#35, seokpan-app#50

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - configmap.yaml
  - database-ca-configmap.yaml
  - deployment.yaml
  - pdb.yaml
  - service.yaml

images:
  - name: harbor.seokpan.soldesk.store/seokpan/backend
    newName: harbor.seokpan.soldesk.store/seokpan/backend
    digest: sha256:c8087963db0783c797b1d97e3168409f89ab6ce5d0b07b5dc3b32255fca69edf
